py_binary(
    name = "conv2d",
    srcs = [
        "conv2d.py",
    ],
    srcs_version = "PY2AND3",
    deps = [
        "//third_party/py/Tkinter",
        "//third_party/py/matplotlib",
        "//third_party/py/numpy",
        "//third_party/py/sklearn",
        "//third_party/py/tensorflow",
    ],
)
